[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mist"
authors = [{name = "Adrian Celaya", email = "aecelaya@rice.edu"}]
dynamic = ["version", "description"]
